# Generated by Django 5.0.3 on 2024-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcontent',
            field=models.TextField(default='insert'),
        ),
    ]
