# Generated by Django 5.0.3 on 2024-09-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_subcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subcontent',
            new_name='summary',
        ),
    ]
