# Generated by Django 5.0.7 on 2024-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cabin_type',
            field=models.TextField(default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='fuel',
            field=models.TextField(default='Benzina', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.TextField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.TextField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default='0', max_length=50),
        ),
    ]
