# Generated by Django 5.0.7 on 2024-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_cabin_type_item_fuel_item_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(default='0'),
        ),
    ]
